name = "saath-cc"
main = "worker.js"
compatibility_date = "2024-09-01"
workers_dev = false
routes = [
  { pattern = "saath.cc", custom_domain = true },
  { pattern = "www.saath.cc", custom_domain = true },
]
