// Lesson depth, written by hand in all three languages. Each array is [English, Hindi, Marathi].
// Run `node scripts/content/build.mjs` after editing to write content/guide.json.
export default {
  budget: {
    cat: "budgeting", icon: "list",
    points: [
      ["Write down every rupee that comes in this month.", "इस महीने जो भी पैसा आता है, सब लिख लें।", "या महिन्यात येणारा प्रत्येक रुपया लिहून ठेवा."],
      ["List what must be paid: rent, travel, fees, food.", "जो देना ही है वह लिखें: किराया, आना-जाना, फीस, खाना।", "जे द्यावेच लागते ते लिहा: भाडे, प्रवास, फी, जेवण."],
      ["What is left is yours to plan, not to guess.", "जो बचता है उसकी योजना बनाएँ, अंदाज़ा न लगाएँ।", "उरलेल्या पैशांचे नियोजन करा, अंदाज नको."],
      ["Look at the list once a week. Two minutes is enough.", "हफ्ते में एक बार सूची देखें। दो मिनट काफी हैं।", "आठवड्यातून एकदा यादी पाहा. दोन मिनिटे पुरतात."],
    ],
    example: ["Asha gets ₹3,000 a month. Bus pass ₹600, mess ₹1,500, phone ₹200. She now knows ₹700 is free, so a ₹900 jacket has to wait one month.", "आशा को महीने के ₹3,000 मिलते हैं। बस पास ₹600, मेस ₹1,500, फोन ₹200। अब उसे पता है कि ₹700 खुले हैं, तो ₹900 की जैकेट एक महीना रुकेगी।", "आशाला महिन्याला ₹3,000 मिळतात. बस पास ₹600, मेस ₹1,500, फोन ₹200. आता तिला कळते की ₹700 मोकळे आहेत, म्हणून ₹900 चे जॅकेट एक महिना थांबेल."],
    try: [["Log what you spent today in Money Lab.", "आज जो खर्च हुआ, मनी लैब में लिखें।", "आज झालेला खर्च मनी लॅबमध्ये नोंदवा."], "tracker"],
    check: {
      q: ["What goes on a budget first?", "बजट में सबसे पहले क्या आता है?", "बजेटमध्ये सर्वात आधी काय येते?"],
      o: [["Things I want to buy", "जो चीज़ें खरीदनी हैं", "ज्या गोष्टी घ्यायच्या आहेत"], ["Money coming in", "आने वाला पैसा", "येणारे पैसे"], ["My friend's spending", "दोस्त का खर्च", "मित्राचा खर्च"]],
      a: 1,
      why: ["You can only plan money you know you have.", "योजना उसी पैसे की बनती है जो सच में आपके पास है।", "जे पैसे खरेच हातात आहेत त्याचेच नियोजन करता येते."],
    },
  },
  "needs-wants": {
    cat: "budgeting", icon: "scale",
    points: [
      ["A need breaks your day if you skip it.", "ज़रूरत वह है जिसे छोड़ें तो दिन बिगड़ जाए।", "गरज म्हणजे जी टाळली तर दिवस बिघडतो."],
      ["A want can move to next week without harm.", "चाहत अगले हफ्ते तक बिना नुकसान रुक सकती है।", "हौस पुढच्या आठवड्यापर्यंत सहज थांबू शकते."],
      ["Pay needs first, on the day money arrives.", "पैसा आते ही पहले ज़रूरतें चुकाएँ।", "पैसे येताच आधी गरजा भागवा."],
      ["Wants are fine. They just come second.", "चाहत गलत नहीं है। बस उसका नंबर दूसरा है।", "हौस चुकीची नाही. फक्त तिचा क्रम दुसरा आहे."],
    ],
    example: ["Ravi has ₹500 left. His exam form costs ₹350 and a movie costs ₹250. The form is a need. The movie moves to next month.", "रवि के पास ₹500 बचे हैं। परीक्षा फॉर्म ₹350 का है और फिल्म ₹250 की। फॉर्म ज़रूरत है। फिल्म अगले महीने।", "रवीकडे ₹500 उरले आहेत. परीक्षेचा फॉर्म ₹350 आणि सिनेमा ₹250. फॉर्म ही गरज आहे. सिनेमा पुढच्या महिन्यात."],
    try: [["Log one need and one want you paid for this week.", "इस हफ्ते की एक ज़रूरत और एक चाहत का खर्च लिखें।", "या आठवड्यातील एक गरज आणि एक हौस यांचा खर्च नोंदवा."], "tracker"],
    check: {
      q: ["Which of these is a need?", "इनमें से ज़रूरत कौन सी है?", "यापैकी गरज कोणती?"],
      o: [["Bus fare to college", "कॉलेज का बस किराया", "कॉलेजचे बस भाडे"], ["New phone cover", "नया फोन कवर", "नवे फोन कव्हर"], ["A second pair of earphones", "दूसरे ईयरफोन", "दुसरे इयरफोन"]],
      a: 0,
      why: ["Without the fare you cannot reach class.", "किराए के बिना आप कक्षा तक नहीं पहुँच सकते।", "भाड्याशिवाय वर्गात पोहोचता येत नाही."],
    },
  },
  "pay-yourself": {
    cat: "budgeting", icon: "piggy",
    points: [
      ["Save on the day money arrives, not at month end.", "पैसा आते ही बचाएँ, महीने के आखिर में नहीं।", "पैसे येताच बाजूला ठेवा, महिन्याच्या शेवटी नाही."],
      ["Start small. Even ₹50 builds the habit.", "छोटे से शुरू करें। ₹50 से भी आदत बनती है।", "लहान सुरुवात करा. ₹50 नेही सवय लागते."],
      ["Keep savings apart from spending money.", "बचत को खर्च के पैसे से अलग रखें।", "बचत खर्चाच्या पैशांपासून वेगळी ठेवा."],
    ],
    example: ["Meena gets ₹2,000 on the 1st. She moves ₹100 to a jar that same morning. In ten months she has ₹1,000 she never missed.", "मीना को 1 तारीख को ₹2,000 मिलते हैं। उसी सुबह वह ₹100 डिब्बे में डाल देती है। दस महीने में ₹1,000 जमा हो जाते हैं और कमी महसूस भी नहीं होती।", "मीनाला 1 तारखेला ₹2,000 मिळतात. त्याच सकाळी ती ₹100 डब्यात टाकते. दहा महिन्यांत ₹1,000 जमतात आणि कमतरता जाणवतही नाही."],
    try: [["Log one saving in Money Lab, however small.", "मनी लैब में एक बचत लिखें, चाहे छोटी हो।", "मनी लॅबमध्ये एक बचत नोंदवा, कितीही लहान असो."], "tracker"],
    check: {
      q: ["When is the best time to save?", "बचत का सबसे अच्छा समय कब है?", "बचतीची सर्वात चांगली वेळ कोणती?"],
      o: [["After all the spending", "सारा खर्च होने के बाद", "सगळा खर्च झाल्यावर"], ["The day money arrives", "जिस दिन पैसा आए", "पैसे येतात त्या दिवशी"], ["Only when a lot is left", "जब बहुत बचे तभी", "खूप उरले तरच"]],
      a: 1,
      why: ["If you wait for what is left, usually nothing is left.", "बचे हुए का इंतज़ार करें तो अक्सर कुछ नहीं बचता।", "उरलेल्याची वाट पाहिली तर सहसा काही उरत नाही."],
    },
  },
  "what-interest": {
    cat: "loans", icon: "percent",
    points: [
      ["Interest is the price of using someone else's money.", "ब्याज किसी और का पैसा इस्तेमाल करने की कीमत है।", "व्याज म्हणजे दुसऱ्याचे पैसे वापरण्याची किंमत."],
      ["When you borrow, you pay it. When you save, you earn it.", "उधार लें तो आप देते हैं। बचाएँ तो आपको मिलता है।", "कर्ज घेतले तर तुम्ही देता. बचत केली तर तुम्हाला मिळते."],
      ["A percent means little alone. Ask for the total in rupees.", "सिर्फ प्रतिशत से कुछ पता नहीं चलता। कुल रकम रुपयों में पूछें।", "नुसत्या टक्क्यांनी काही कळत नाही. एकूण रक्कम रुपयांत विचारा."],
    ],
    example: ["Borrow ₹10,000 at 12 percent for one year and you pay back about ₹11,200. The extra ₹1,200 is the interest.", "₹10,000 एक साल के लिए 12 प्रतिशत पर लें तो करीब ₹11,200 लौटाने होंगे। ऊपर के ₹1,200 ब्याज हैं।", "₹10,000 एका वर्षासाठी 12 टक्क्यांनी घेतले तर सुमारे ₹11,200 परत द्यावे लागतात. वरचे ₹1,200 म्हणजे व्याज."],
    try: [["Open the gold loan sample and find the interest line.", "गोल्ड लोन का नमूना खोलें और ब्याज वाली लाइन ढूँढें।", "गोल्ड लोनचा नमुना उघडा आणि व्याजाची ओळ शोधा."], "scan:gold-loan"],
    check: {
      q: ["You borrow ₹5,000 and pay back ₹5,600. How much is interest?", "आपने ₹5,000 लिए और ₹5,600 लौटाए। ब्याज कितना हुआ?", "तुम्ही ₹5,000 घेतले आणि ₹5,600 परत दिले. व्याज किती?"],
      o: [["₹600", "₹600", "₹600"], ["₹5,600", "₹5,600", "₹5,600"], ["₹5,000", "₹5,000", "₹5,000"]],
      a: 0,
      why: ["Interest is what you pay above the amount you borrowed.", "ब्याज वह है जो उधार की रकम से ऊपर देना पड़ता है।", "घेतलेल्या रकमेपेक्षा जास्त द्यावे लागते ते व्याज."],
    },
  },
  "simple-compound": {
    cat: "loans", icon: "trending",
    points: [
      ["Simple interest is charged only on the starting amount.", "साधारण ब्याज सिर्फ शुरुआती रकम पर लगता है।", "सरळ व्याज फक्त सुरुवातीच्या रकमेवर लागते."],
      ["Compound interest is charged on the amount plus old interest.", "चक्रवृद्धि ब्याज रकम और पुराने ब्याज, दोनों पर लगता है।", "चक्रवाढ व्याज रक्कम आणि जुने व्याज, दोन्हींवर लागते."],
      ["Compound helps your savings grow faster.", "चक्रवृद्धि से बचत तेज़ बढ़ती है।", "चक्रवाढीमुळे बचत वेगाने वाढते."],
      ["Compound hurts when a bill is left unpaid.", "बिल बाकी रह जाए तो चक्रवृद्धि नुकसान करता है।", "बिल थकले तर चक्रवाढ नुकसान करते."],
    ],
    example: ["₹1,000 at 10 percent. Simple: ₹100 every year. Compound: ₹100 the first year, ₹110 the second, ₹121 the third.", "₹1,000 पर 10 प्रतिशत। साधारण: हर साल ₹100। चक्रवृद्धि: पहले साल ₹100, दूसरे साल ₹110, तीसरे साल ₹121।", "₹1,000 वर 10 टक्के. सरळ: दरवर्षी ₹100. चक्रवाढ: पहिल्या वर्षी ₹100, दुसऱ्या वर्षी ₹110, तिसऱ्या वर्षी ₹121."],
    try: [["Ask at home whether any bill or card has unpaid interest growing on it.", "घर पर पूछें कि किसी बिल या कार्ड पर बकाया ब्याज तो नहीं बढ़ रहा।", "घरी विचारा की एखाद्या बिलावर किंवा कार्डावर थकीत व्याज वाढत तर नाही ना."], null],
    check: {
      q: ["Which kind grows on its own growth?", "कौन सा ब्याज अपने ही ब्याज पर बढ़ता है?", "कोणते व्याज स्वतःच्याच व्याजावर वाढते?"],
      o: [["Simple", "साधारण", "सरळ"], ["Compound", "चक्रवृद्धि", "चक्रवाढ"], ["Neither", "कोई नहीं", "कोणतेही नाही"]],
      a: 1,
      why: ["Compound adds interest back in, so the next interest is larger.", "चक्रवृद्धि में ब्याज रकम में जुड़ जाता है, इसलिए अगला ब्याज बड़ा होता है।", "चक्रवाढीत व्याज रकमेत मिसळते, म्हणून पुढचे व्याज मोठे होते."],
    },
  },
  "what-emi": {
    cat: "loans", icon: "calendar",
    points: [
      ["An EMI is the same payment every month.", "ईएमआई हर महीने की एक जैसी किस्त है।", "ईएमआय म्हणजे दर महिन्याचा सारखाच हप्ता."],
      ["Each EMI has some loan and some interest inside it.", "हर किस्त में थोड़ा कर्ज और थोड़ा ब्याज होता है।", "प्रत्येक हप्त्यात थोडे कर्ज आणि थोडे व्याज असते."],
      ["EMI times months gives the real total.", "किस्त को महीनों से गुणा करें तो असली कुल रकम मिलती है।", "हप्ता गुणिले महिने म्हणजे खरी एकूण रक्कम."],
      ["A small EMI over many months can cost the most.", "छोटी किस्त और लंबा समय सबसे महँगा पड़ सकता है।", "लहान हप्ता आणि जास्त महिने सर्वात महाग ठरू शकतात."],
    ],
    example: ["A phone costs ₹12,000. The shop offers ₹1,250 for 12 months. 1,250 times 12 is ₹15,000. The phone costs ₹3,000 more this way.", "फोन ₹12,000 का है। दुकान 12 महीने के लिए ₹1,250 की किस्त देती है। 1,250 गुणा 12 यानी ₹15,000। इस तरह फोन ₹3,000 महँगा पड़ता है।", "फोन ₹12,000 चा आहे. दुकान 12 महिन्यांसाठी ₹1,250 चा हप्ता देते. 1,250 गुणिले 12 म्हणजे ₹15,000. अशा प्रकारे फोन ₹3,000 ने महाग पडतो."],
    try: [["Open the personal loan sample and see the total for 24 EMIs.", "पर्सनल लोन का नमूना खोलें और 24 किस्तों का कुल देखें।", "पर्सनल लोनचा नमुना उघडा आणि 24 हप्त्यांची एकूण रक्कम पाहा."], "scan:personal-loan"],
    check: {
      q: ["EMI is ₹2,000 for 10 months. What is the total?", "किस्त ₹2,000 है, 10 महीने के लिए। कुल कितना?", "हप्ता ₹2,000, 10 महिन्यांसाठी. एकूण किती?"],
      o: [["₹2,000", "₹2,000", "₹2,000"], ["₹12,000", "₹12,000", "₹12,000"], ["₹20,000", "₹20,000", "₹20,000"]],
      a: 2,
      why: ["Multiply the EMI by the number of months.", "किस्त को महीनों की गिनती से गुणा करें।", "हप्त्याला महिन्यांच्या संख्येने गुणा."],
    },
  },
  "flat-reducing": {
    cat: "loans", icon: "split",
    points: [
      ["Flat: interest on the full amount for the whole time.", "फ्लैट: पूरे समय पूरी रकम पर ब्याज।", "फ्लॅट: पूर्ण काळ पूर्ण रकमेवर व्याज."],
      ["Reducing: interest only on what you still owe.", "घटता: ब्याज सिर्फ बची हुई रकम पर।", "कमी होणारे: व्याज फक्त उरलेल्या रकमेवर."],
      ["The same percent costs much more on a flat rate.", "एक ही प्रतिशत फ्लैट में बहुत महँगा पड़ता है।", "तेवढेच टक्के फ्लॅटमध्ये खूप महाग पडतात."],
      ["Always ask which kind, then ask for both totals.", "हमेशा पूछें कौन सा है, फिर दोनों का कुल पूछें।", "नेहमी विचारा कोणता प्रकार, मग दोन्हींची एकूण रक्कम विचारा."],
    ],
    example: ["₹1,00,000 at 12 percent for one year. Flat: you pay back ₹1,12,000. Reducing: about ₹1,06,600. The paper says 12 percent both times.", "₹1,00,000, 12 प्रतिशत, एक साल। फ्लैट: ₹1,12,000 लौटाने होंगे। घटता: करीब ₹1,06,600। कागज़ पर दोनों बार 12 प्रतिशत ही लिखा है।", "₹1,00,000, 12 टक्के, एक वर्ष. फ्लॅट: ₹1,12,000 परत द्यावे लागतात. कमी होणारे: सुमारे ₹1,06,600. कागदावर दोन्ही वेळा 12 टक्केच लिहिलेले असते."],
    try: [["Open the personal loan sample and compare the flat and reducing totals.", "पर्सनल लोन का नमूना खोलें और फ्लैट व घटते का कुल मिलाकर देखें।", "पर्सनल लोनचा नमुना उघडा आणि फ्लॅट व कमी होणाऱ्या दराची एकूण रक्कम तुलना करा."], "scan:personal-loan"],
    check: {
      q: ["Two loans both say 12 percent. Which usually costs less?", "दो कर्ज, दोनों पर 12 प्रतिशत लिखा है। आम तौर पर कौन सस्ता है?", "दोन कर्जे, दोन्हींवर 12 टक्के. सहसा कोणते स्वस्त?"],
      o: [["The flat one", "फ्लैट वाला", "फ्लॅट दराचे"], ["The reducing one", "घटते ब्याज वाला", "कमी होणाऱ्या दराचे"], ["They cost the same", "दोनों बराबर", "दोन्ही सारखेच"]],
      a: 1,
      why: ["Reducing interest falls as you repay. Flat interest does not.", "घटता ब्याज चुकाने के साथ कम होता है। फ्लैट नहीं होता।", "परतफेड होईल तसे कमी होणारे व्याज घटते. फ्लॅट घटत नाही."],
    },
  },
  fees: {
    cat: "loans", icon: "receipt",
    points: [
      ["A processing fee is often cut before you get the money.", "प्रोसेसिंग शुल्क अक्सर पैसा मिलने से पहले ही काट लिया जाता है।", "प्रोसेसिंग शुल्क बहुधा पैसे मिळण्याआधीच कापले जाते."],
      ["So you receive less, but repay the full amount.", "इसलिए हाथ में कम आता है, पर लौटाना पूरा पड़ता है।", "म्हणून हातात कमी येते, पण परत पूर्ण द्यावे लागते."],
      ["Add every charge in rupees, including GST.", "हर शुल्क रुपयों में जोड़ें, जीएसटी भी।", "प्रत्येक शुल्क रुपयांत मिळवा, जीएसटीसह."],
      ["Fees above 3 percent of the loan are high.", "कर्ज के 3 प्रतिशत से ज़्यादा शुल्क ज़्यादा माना जाता है।", "कर्जाच्या 3 टक्क्यांपेक्षा जास्त शुल्क जास्त मानले जाते."],
    ],
    example: ["Loan ₹50,000. Processing fee ₹1,500 and document charge ₹500. You get ₹48,000 in hand but pay interest on ₹50,000.", "कर्ज ₹50,000। प्रोसेसिंग शुल्क ₹1,500 और दस्तावेज़ शुल्क ₹500। हाथ में ₹48,000 आते हैं, पर ब्याज ₹50,000 पर लगता है।", "कर्ज ₹50,000. प्रोसेसिंग शुल्क ₹1,500 आणि कागदपत्र शुल्क ₹500. हातात ₹48,000 येतात, पण व्याज ₹50,000 वर लागते."],
    try: [["Open the personal loan sample and find both fees.", "पर्सनल लोन का नमूना खोलें और दोनों शुल्क ढूँढें।", "पर्सनल लोनचा नमुना उघडा आणि दोन्ही शुल्क शोधा."], "scan:personal-loan"],
    check: {
      q: ["Loan ₹20,000, fee ₹1,000 cut first. How much reaches you?", "कर्ज ₹20,000, शुल्क ₹1,000 पहले कटा। आपके हाथ में कितना आया?", "कर्ज ₹20,000, शुल्क ₹1,000 आधी कापले. हातात किती आले?"],
      o: [["₹21,000", "₹21,000", "₹21,000"], ["₹20,000", "₹20,000", "₹20,000"], ["₹19,000", "₹19,000", "₹19,000"]],
      a: 2,
      why: ["The fee leaves before the money reaches you.", "शुल्क पैसा मिलने से पहले ही निकल जाता है।", "पैसे मिळण्याआधीच शुल्क निघून जाते."],
    },
  },
  prepayment: {
    cat: "loans", icon: "unlock",
    points: [
      ["Prepayment means closing a loan before its end date.", "पूर्वभुगतान यानी कर्ज को तय समय से पहले चुका देना।", "पूर्वफेड म्हणजे कर्ज ठरलेल्या वेळेआधी फेडणे."],
      ["Closing early saves the interest of the remaining months.", "जल्दी चुकाने से बचे महीनों का ब्याज बचता है।", "लवकर फेडल्याने उरलेल्या महिन्यांचे व्याज वाचते."],
      ["Some papers forbid it or charge a fee for it.", "कुछ कागज़ इसे मना करते हैं या इस पर शुल्क लगाते हैं।", "काही करार याला मनाई करतात किंवा त्यावर शुल्क लावतात."],
    ],
    example: ["Sunil gets a scholarship in month six of a 24 month loan. His paper says prepayment is not permitted, so he must keep paying interest for 18 more months.", "सुनील को 24 महीने के कर्ज के छठे महीने में छात्रवृत्ति मिलती है। कागज़ में पूर्वभुगतान मना है, इसलिए उसे 18 महीने और ब्याज देना पड़ता है।", "सुनीलला 24 महिन्यांच्या कर्जाच्या सहाव्या महिन्यात शिष्यवृत्ती मिळते. करारात पूर्वफेडीला मनाई आहे, म्हणून त्याला आणखी 18 महिने व्याज द्यावे लागते."],
    try: [["Open the gold loan sample and read the prepayment line.", "गोल्ड लोन का नमूना खोलें और पूर्वभुगतान की लाइन पढ़ें।", "गोल्ड लोनचा नमुना उघडा आणि पूर्वफेडीची ओळ वाचा."], "scan:gold-loan"],
    check: {
      q: ["Why ask about prepayment before signing?", "साइन करने से पहले पूर्वभुगतान के बारे में क्यों पूछें?", "सही करण्यापूर्वी पूर्वफेडीबद्दल का विचारावे?"],
      o: [["So I can close early and save interest", "ताकि जल्दी चुकाकर ब्याज बचा सकूँ", "लवकर फेडून व्याज वाचवता यावे म्हणून"], ["It makes the EMI smaller", "इससे किस्त छोटी होती है", "त्याने हप्ता लहान होतो"], ["It is only for big companies", "यह सिर्फ बड़ी कंपनियों के लिए है", "ते फक्त मोठ्या कंपन्यांसाठी असते"]],
      a: 0,
      why: ["If money comes later, an early close can save a lot.", "आगे पैसा आ जाए तो जल्दी चुकाने से काफी बचत होती है।", "पुढे पैसे आले तर लवकर फेडल्याने बरीच बचत होते."],
    },
  },
  "credit-score": {
    cat: "loans", icon: "gauge",
    points: [
      ["A credit score is a number that shows how you repaid before.", "क्रेडिट स्कोर एक नंबर है जो बताता है आपने पहले कैसे चुकाया।", "क्रेडिट स्कोअर हा एक आकडा आहे, जो तुम्ही आधी कशी परतफेड केली ते सांगतो."],
      ["Paying on the due date keeps it healthy.", "तय तारीख पर चुकाने से यह अच्छा रहता है।", "ठरलेल्या तारखेला भरल्याने तो चांगला राहतो."],
      ["A missed EMI stays on the record for years.", "छूटी हुई किस्त सालों तक रिकॉर्ड में रहती है।", "चुकलेला हप्ता वर्षानुवर्षे नोंदीत राहतो."],
      ["You can check your own report once a year for free.", "आप अपनी रिपोर्ट साल में एक बार मुफ्त देख सकते हैं।", "तुम्ही तुमचा अहवाल वर्षातून एकदा मोफत पाहू शकता."],
    ],
    example: ["Farah missed two EMIs on a ₹8,000 phone loan. Three years later a bank offers her an education loan at a higher rate because of that record.", "फराह ने ₹8,000 के फोन लोन की दो किस्तें छोड़ दीं। तीन साल बाद उसी रिकॉर्ड की वजह से बैंक उसे पढ़ाई का कर्ज ज़्यादा ब्याज पर देता है।", "फराहने ₹8,000 च्या फोन कर्जाचे दोन हप्ते चुकवले. तीन वर्षांनी त्याच नोंदीमुळे बँक तिला शिक्षण कर्ज जास्त व्याजाने देते."],
    try: [["Ask a parent whether any loan or card is in your name.", "माता-पिता से पूछें कि आपके नाम पर कोई कर्ज या कार्ड तो नहीं।", "आईवडिलांना विचारा की तुमच्या नावावर एखादे कर्ज किंवा कार्ड आहे का."], null],
    check: {
      q: ["What helps a credit score most?", "क्रेडिट स्कोर को सबसे ज़्यादा क्या सुधारता है?", "क्रेडिट स्कोअरला सर्वात जास्त काय मदत करते?"],
      o: [["Taking many loans", "बहुत सारे कर्ज लेना", "खूप कर्जे घेणे"], ["Paying on time, every time", "हर बार समय पर चुकाना", "प्रत्येक वेळी वेळेवर भरणे"], ["Never checking it", "उसे कभी न देखना", "तो कधीच न पाहणे"]],
      a: 1,
      why: ["Lenders look first at whether you paid on time.", "कर्ज देने वाले सबसे पहले देखते हैं कि आपने समय पर चुकाया या नहीं।", "कर्ज देणारे आधी पाहतात की तुम्ही वेळेवर भरले की नाही."],
    },
  },
  "reading-agreement": {
    cat: "loans", icon: "file",
    points: [
      ["Find six things: amount, rate, time, fees, penalty, early closing.", "छह चीज़ें ढूँढें: रकम, दर, समय, शुल्क, जुर्माना, जल्दी चुकाना।", "सहा गोष्टी शोधा: रक्कम, दर, कालावधी, शुल्क, दंड, लवकर फेड."],
      ["Check whether the rate is flat or reducing.", "देखें कि दर फ्लैट है या घटती।", "दर फ्लॅट आहे की कमी होणारा ते पाहा."],
      ["Never sign a paper with blank spaces.", "खाली जगह वाले कागज़ पर कभी साइन न करें।", "रिकाम्या जागा असलेल्या कागदावर कधीही सही करू नका."],
      ["Ask for a copy. It is your right.", "एक कॉपी माँगें। यह आपका हक है।", "एक प्रत मागा. तो तुमचा हक्क आहे."],
    ],
    example: ["Imran's paper names the amount and the EMI but leaves the penalty line blank. He asks the agent to write it in before he signs.", "इमरान के कागज़ में रकम और किस्त लिखी है, पर जुर्माने की लाइन खाली है। वह साइन करने से पहले एजेंट से उसे भरवाता है।", "इमरानच्या करारात रक्कम आणि हप्ता लिहिला आहे, पण दंडाची ओळ रिकामी आहे. सही करण्याआधी तो एजंटकडून ती भरून घेतो."],
    try: [["Scan the personal loan sample and tick off all six things.", "पर्सनल लोन का नमूना स्कैन करें और छहों चीज़ें मिलाएँ।", "पर्सनल लोनचा नमुना स्कॅन करा आणि सहाही गोष्टी तपासा."], "scan:personal-loan"],
    check: {
      q: ["The penalty line is blank. What do you do?", "जुर्माने की लाइन खाली है। आप क्या करेंगे?", "दंडाची ओळ रिकामी आहे. तुम्ही काय कराल?"],
      o: [["Sign, it is probably zero", "साइन कर दूँ, शायद शून्य होगा", "सही करीन, बहुधा शून्य असेल"], ["Ask them to fill it in first", "पहले उसे भरवाऊँ", "आधी ती भरून घेईन"], ["Fill it myself later", "बाद में खुद भर लूँ", "नंतर स्वतः भरीन"]],
      a: 1,
      why: ["A blank can be filled later with terms you never agreed to.", "खाली जगह बाद में ऐसी शर्तों से भरी जा सकती है जो आपने मानी ही नहीं।", "रिकामी जागा नंतर तुम्ही मान्य न केलेल्या अटींनी भरली जाऊ शकते."],
    },
  },
  "upi-safety": {
    cat: "scams", icon: "phone",
    points: [
      ["You enter your UPI PIN only to send money.", "यूपीआई पिन सिर्फ पैसा भेजने के लिए डाला जाता है।", "यूपीआय पिन फक्त पैसे पाठवण्यासाठी टाकला जातो."],
      ["Receiving money never needs a PIN or a scan.", "पैसा पाने के लिए कभी पिन या स्कैन नहीं लगता।", "पैसे मिळवण्यासाठी कधीही पिन किंवा स्कॅन लागत नाही."],
      ["Decline a collect request you did not expect.", "जो रिक्वेस्ट आपने नहीं माँगी, उसे मना कर दें।", "तुम्ही न मागितलेली रिक्वेस्ट नाकारा."],
      ["Check the name on screen before you pay.", "पैसा भेजने से पहले स्क्रीन पर नाम देख लें।", "पैसे पाठवण्याआधी स्क्रीनवरील नाव तपासा."],
    ],
    example: ["A buyer on a resale app says “I sent ₹2,000, enter your PIN to accept.” Pooja declines. Entering the PIN would have sent ₹2,000 out of her account.", "एक खरीदार कहता है, “मैंने ₹2,000 भेजे हैं, लेने के लिए पिन डालो।” पूजा मना कर देती है। पिन डालने पर ₹2,000 उसके खाते से निकल जाते।", "एक खरेदीदार म्हणतो, “मी ₹2,000 पाठवले, घेण्यासाठी पिन टाका.” पूजा नकार देते. पिन टाकला असता तर ₹2,000 तिच्या खात्यातून गेले असते."],
    try: [["Read this week's case about a helpful caller.", "मददगार कॉलर वाला मामला पढ़ें।", "मदत करणाऱ्या कॉलरचा प्रसंग वाचा."], "case:upi-pin"],
    check: {
      q: ["Someone will send you money. Do you need your PIN?", "कोई आपको पैसा भेजेगा। क्या पिन चाहिए?", "कोणी तुम्हाला पैसे पाठवणार आहे. पिन लागतो का?"],
      o: [["Yes, to accept it", "हाँ, लेने के लिए", "हो, स्वीकारण्यासाठी"], ["No, never", "नहीं, कभी नहीं", "नाही, कधीच नाही"], ["Only for large amounts", "सिर्फ बड़ी रकम के लिए", "फक्त मोठ्या रकमेसाठी"]],
      a: 1,
      why: ["A PIN only sends money out. It never brings money in.", "पिन से पैसा सिर्फ जाता है। आता कभी नहीं।", "पिनने पैसे फक्त जातात. येत कधीच नाहीत."],
    },
  },
  "otp-pin": {
    cat: "scams", icon: "key",
    points: [
      ["An OTP is a one-time key to your money.", "ओटीपी आपके पैसे की एक बार की चाबी है।", "ओटीपी म्हणजे तुमच्या पैशांची एकदाच वापरायची किल्ली."],
      ["No bank, shop or helpline will ask you to read it out.", "कोई बैंक, दुकान या हेल्पलाइन इसे बोलकर बताने को नहीं कहती।", "कोणतीही बँक, दुकान किंवा हेल्पलाइन तो सांगायला लावत नाही."],
      ["Read the message. It names the amount and who gets it.", "मैसेज पढ़ें। उसमें रकम और पाने वाले का नाम होता है।", "मेसेज वाचा. त्यात रक्कम आणि पैसे कोणाला जाणार ते असते."],
    ],
    example: ["A caller says Dev's SIM will be blocked unless he shares the code just sent. The message reads “OTP for payment of ₹4,999”. Dev hangs up.", "फोन पर कोई कहता है कि देव का सिम बंद हो जाएगा, अभी आया कोड बताओ। मैसेज में लिखा है “₹4,999 के भुगतान का ओटीपी”। देव फोन काट देता है।", "फोनवर कोणी सांगतो की देवचे सिम बंद होईल, आत्ता आलेला कोड सांगा. मेसेजमध्ये लिहिले आहे “₹4,999 च्या पेमेंटचा ओटीपी”. देव फोन ठेवतो."],
    try: [["Open your last OTP message and read what it was for.", "अपना पिछला ओटीपी मैसेज खोलें और पढ़ें कि वह किस काम का था।", "तुमचा शेवटचा ओटीपी मेसेज उघडा आणि तो कशासाठी होता ते वाचा."], null],
    check: {
      q: ["A “bank officer” on a call asks for your OTP. You:", "फोन पर “बैंक अधिकारी” ओटीपी माँगता है। आप:", "फोनवर “बँक अधिकारी” ओटीपी मागतो. तुम्ही:"],
      o: [["Share it quickly", "जल्दी बता दें", "लगेच सांगाल"], ["Hang up", "फोन काट दें", "फोन ठेवाल"], ["Share only half", "आधा ही बताएँ", "अर्धाच सांगाल"]],
      a: 1,
      why: ["A real bank never asks for an OTP on a call.", "असली बैंक फोन पर कभी ओटीपी नहीं माँगता।", "खरी बँक फोनवर कधीही ओटीपी मागत नाही."],
    },
  },
};
