// Second half of the lesson depth. Each array is [English, Hindi, Marathi].
export default {
  "fake-loan-apps": {
    cat: "scams", icon: "shield",
    points: [
      ["A real lender is registered. Its name is on the RBI list.", "असली कर्ज देने वाला रजिस्टर्ड होता है। उसका नाम आरबीआई की सूची में मिलता है।", "खरा कर्जदाता नोंदणीकृत असतो. त्याचे नाव आरबीआयच्या यादीत असते."],
      ["A loan app does not need your contacts or photos.", "लोन ऐप को आपके कॉन्टैक्ट या फोटो की ज़रूरत नहीं होती।", "लोन अ‍ॅपला तुमचे संपर्क किंवा फोटो लागत नाहीत."],
      ["Loans of seven days with huge fees are a warning sign.", "सात दिन का कर्ज और भारी शुल्क खतरे का संकेत है।", "सात दिवसांचे कर्ज आणि भरमसाट शुल्क हे धोक्याचे लक्षण आहे."],
      ["If an app threatens you, tell family and report it at 1930.", "ऐप धमकाए तो घर पर बताएँ और 1930 पर शिकायत करें।", "अ‍ॅपने धमकावले तर घरी सांगा आणि 1930 वर तक्रार करा."],
    ],
    example: ["An app gives Kiran ₹3,000 for seven days, keeps ₹900 as fees, and wants ₹3,000 back. When she is late by a day it messages her whole phone book.", "एक ऐप किरण को सात दिन के लिए ₹3,000 देता है, ₹900 शुल्क में रख लेता है, और पूरे ₹3,000 वापस माँगता है। एक दिन देर होने पर वह उसके सारे कॉन्टैक्ट को मैसेज कर देता है।", "एक अ‍ॅप किरणला सात दिवसांसाठी ₹3,000 देते, ₹900 शुल्क म्हणून ठेवते, आणि पूर्ण ₹3,000 परत मागते. एक दिवस उशीर झाल्यावर ते तिच्या सगळ्या संपर्कांना मेसेज करते."],
    try: [["Read the case about the app that wants the phone book.", "फोन बुक माँगने वाले ऐप का मामला पढ़ें।", "फोन बुक मागणाऱ्या अ‍ॅपचा प्रसंग वाचा."], "case:payday-app"],
    check: {
      q: ["A loan app asks to read your contacts. You:", "लोन ऐप आपके कॉन्टैक्ट पढ़ने की इजाज़त माँगता है। आप:", "लोन अ‍ॅप तुमचे संपर्क वाचण्याची परवानगी मागते. तुम्ही:"],
      o: [["Allow, it is normal", "दे दें, यह आम बात है", "द्याल, हे नेहमीचे आहे"], ["Stop and uninstall", "रुकें और ऐप हटा दें", "थांबाल आणि अ‍ॅप काढून टाकाल"], ["Allow only for one day", "एक दिन के लिए दे दें", "एका दिवसासाठी द्याल"]],
      a: 1,
      why: ["Contacts are used to shame borrowers, not to lend.", "कॉन्टैक्ट का इस्तेमाल कर्ज देने में नहीं, बदनाम करने में होता है।", "संपर्क कर्ज देण्यासाठी नाही, बदनामी करण्यासाठी वापरले जातात."],
    },
  },
  "job-scams": {
    cat: "scams", icon: "briefcase",
    points: [
      ["A real job or scholarship never asks you to pay first.", "असली नौकरी या छात्रवृत्ति कभी पहले पैसा नहीं माँगती।", "खरी नोकरी किंवा शिष्यवृत्ती कधीही आधी पैसे मागत नाही."],
      ["“Registration fee” and “refundable deposit” are common tricks.", "“रजिस्ट्रेशन फीस” और “वापस मिलने वाली जमा” आम चालें हैं।", "“नोंदणी शुल्क” आणि “परत मिळणारी ठेव” या नेहमीच्या युक्त्या आहेत."],
      ["Check the offer on the official website you typed yourself.", "ऑफर को उस सरकारी साइट पर जाँचें जिसका पता आपने खुद लिखा हो।", "ऑफर अधिकृत साइटवर तपासा, पत्ता स्वतः टाइप करून."],
      ["Being rushed is a reason to slow down.", "जल्दी मचाई जाए तो और धीरे चलें।", "घाई केली जात असेल तर आणखी सावकाश व्हा."],
    ],
    example: ["A message says Neha won a ₹50,000 scholarship and must pay ₹499 today to confirm. Her college office has never heard of it. She does not pay.", "मैसेज आता है कि नेहा को ₹50,000 की छात्रवृत्ति मिली है, पक्की करने के लिए आज ₹499 भरें। कॉलेज के दफ़्तर को इसकी कोई खबर नहीं। नेहा पैसा नहीं भरती।", "मेसेज येतो की नेहाला ₹50,000 ची शिष्यवृत्ती मिळाली आहे, नक्की करण्यासाठी आज ₹499 भरा. कॉलेजच्या कार्यालयाला याची माहितीच नाही. नेहा पैसे भरत नाही."],
    try: [["Ask your college office which scholarship sites are real.", "कॉलेज के दफ़्तर से पूछें कि छात्रवृत्ति की कौन सी साइटें असली हैं।", "कॉलेजच्या कार्यालयात विचारा की शिष्यवृत्तीच्या कोणत्या साइट खऱ्या आहेत."], null],
    check: {
      q: ["A “recruiter” wants ₹1,000 for a training kit before the job starts.", "“भर्ती करने वाला” नौकरी से पहले ट्रेनिंग किट के ₹1,000 माँगता है।", "“भरती करणारा” नोकरी सुरू होण्याआधी ट्रेनिंग किटसाठी ₹1,000 मागतो."],
      o: [["Pay, it is refundable", "भर दें, वापस मिल जाएगा", "भराल, परत मिळतील"], ["Do not pay", "पैसा न दें", "पैसे देणार नाही"], ["Pay half", "आधा दे दें", "अर्धे द्याल"]],
      a: 1,
      why: ["Employers pay you. They do not charge you to start.", "नौकरी देने वाला आपको पैसा देता है, आपसे लेता नहीं।", "नोकरी देणारा तुम्हाला पैसे देतो, तुमच्याकडून घेत नाही."],
    },
  },
  "what-insurance": {
    cat: "insurance", icon: "umbrella",
    points: [
      ["You pay a small premium so a big loss does not break the family.", "आप छोटा प्रीमियम देते हैं ताकि बड़ा नुकसान घर को न तोड़े।", "तुम्ही छोटा हप्ता भरता, जेणेकरून मोठे नुकसान घर मोडणार नाही."],
      ["Sum assured is the most the policy will pay.", "बीमा राशि वह सबसे बड़ी रकम है जो पॉलिसी देगी।", "विमा रक्कम म्हणजे पॉलिसी जास्तीत जास्त किती देईल ती रक्कम."],
      ["Insurance is protection. It is not a savings plan.", "बीमा सुरक्षा है। यह बचत की योजना नहीं है।", "विमा म्हणजे संरक्षण. ती बचत योजना नाही."],
    ],
    example: ["A family pays ₹500 a month for health cover of ₹5,00,000. When the father needs a ₹1,20,000 operation, the policy pays the hospital.", "एक परिवार ₹5,00,000 के हेल्थ कवर के लिए महीने के ₹500 देता है। पिता के ₹1,20,000 के ऑपरेशन का बिल पॉलिसी भरती है।", "एक कुटुंब ₹5,00,000 च्या आरोग्य विम्यासाठी महिन्याला ₹500 भरते. वडिलांच्या ₹1,20,000 च्या ऑपरेशनचे बिल पॉलिसी भरते."],
    try: [["Ask at home which insurance the family has, and where the papers are.", "घर पर पूछें कि परिवार के पास कौन सा बीमा है और कागज़ कहाँ रखे हैं।", "घरी विचारा की कुटुंबाकडे कोणता विमा आहे आणि कागदपत्रे कुठे आहेत."], null],
    check: {
      q: ["An agent says a policy “doubles your money like an FD”. You:", "एजेंट कहता है पॉलिसी “एफडी की तरह पैसा दोगुना करती है”। आप:", "एजंट म्हणतो पॉलिसी “एफडीसारखे पैसे दुप्पट करते”. तुम्ही:"],
      o: [["Buy it today", "आज ही ले लें", "आजच घ्याल"], ["Ask to see all the costs in writing", "सारे खर्च लिखकर माँगें", "सगळे खर्च लेखी मागाल"], ["Buy two", "दो ले लें", "दोन घ्याल"]],
      a: 1,
      why: ["Mixing insurance with investment often hides high charges.", "बीमा और निवेश को मिलाने में अक्सर भारी शुल्क छिपे होते हैं।", "विमा आणि गुंतवणूक एकत्र केल्यावर बहुधा मोठे शुल्क लपलेले असते."],
    },
  },
  "health-cover": {
    cat: "insurance", icon: "heart",
    points: [
      ["Check which hospitals near you accept the policy.", "देखें कि आपके पास के कौन से अस्पताल पॉलिसी मानते हैं।", "तुमच्या जवळची कोणती रुग्णालये पॉलिसी स्वीकारतात ते पाहा."],
      ["Know what you must pay yourself before the policy pays.", "जानें कि पॉलिसी के देने से पहले आपको खुद कितना देना है।", "पॉलिसी देण्याआधी तुम्हाला स्वतः किती भरावे लागते ते जाणून घ्या."],
      ["Read the list of illnesses that are not covered.", "उन बीमारियों की सूची पढ़ें जो कवर में नहीं हैं।", "ज्या आजारांना संरक्षण नाही त्यांची यादी वाचा."],
      ["Keep every bill and discharge paper for the claim.", "क्लेम के लिए हर बिल और डिस्चार्ज का कागज़ सँभालकर रखें।", "दाव्यासाठी प्रत्येक बिल आणि डिस्चार्जचा कागद जपून ठेवा."],
    ],
    example: ["Ayushman Bharat covers up to ₹5,00,000 a year for families that qualify. Lata checks her family's name on the official site before the hospital visit.", "आयुष्मान भारत पात्र परिवारों को साल में ₹5,00,000 तक का कवर देता है। लता अस्पताल जाने से पहले सरकारी साइट पर अपने परिवार का नाम देख लेती है।", "आयुष्मान भारत पात्र कुटुंबांना वर्षाला ₹5,00,000 पर्यंत संरक्षण देते. लता रुग्णालयात जाण्याआधी अधिकृत साइटवर कुटुंबाचे नाव तपासते."],
    try: [["Find out if your family has a health card, and where it is kept.", "पता करें कि परिवार के पास हेल्थ कार्ड है या नहीं, और कहाँ रखा है।", "कुटुंबाकडे आरोग्य कार्ड आहे का आणि ते कुठे ठेवले आहे ते शोधा."], null],
    check: {
      q: ["A cheap policy does not include the hospital in your town. Is it a good deal?", "सस्ती पॉलिसी में आपके शहर का अस्पताल नहीं है। क्या यह फायदे का सौदा है?", "स्वस्त पॉलिसीत तुमच्या गावातील रुग्णालय नाही. हा फायद्याचा सौदा आहे का?"],
      o: [["Yes, cheap is best", "हाँ, सस्ता सबसे अच्छा", "हो, स्वस्त तेच उत्तम"], ["No, I could not use it", "नहीं, मैं इसे इस्तेमाल ही नहीं कर पाऊँगा", "नाही, ती वापरताच येणार नाही"], ["It makes no difference", "कोई फर्क नहीं पड़ता", "काही फरक पडत नाही"]],
      a: 1,
      why: ["Cover you cannot reach in an emergency does not protect you.", "जो कवर ज़रूरत के समय काम न आए, वह सुरक्षा नहीं देता।", "गरजेच्या वेळी उपयोगी न पडणारे संरक्षण काही कामाचे नाही."],
    },
  },
  "emergency-fund": {
    cat: "savings", icon: "jar",
    points: [
      ["An emergency fund is money kept only for sudden needs.", "आपातकालीन फंड वह पैसा है जो सिर्फ अचानक की ज़रूरत के लिए रखा जाता है।", "आपत्कालीन निधी म्हणजे फक्त अचानक गरजेसाठी ठेवलेले पैसे."],
      ["Start with a first goal of ₹1,000.", "पहला लक्ष्य ₹1,000 रखें।", "पहिले लक्ष्य ₹1,000 ठेवा."],
      ["Keep it where you can reach it the same day.", "इसे वहाँ रखें जहाँ से उसी दिन निकाल सकें।", "ते अशा ठिकाणी ठेवा जिथून त्याच दिवशी काढता येईल."],
      ["A sale or a party is not an emergency.", "सेल या पार्टी आपातकाल नहीं है।", "सेल किंवा पार्टी म्हणजे आपत्काल नाही."],
    ],
    example: ["Arjun's phone screen cracks a week before online exams. The repair is ₹900. He pays from his jar instead of borrowing from an app.", "ऑनलाइन परीक्षा से एक हफ्ता पहले अर्जुन के फोन की स्क्रीन टूट जाती है। मरम्मत ₹900 की है। वह ऐप से उधार लेने के बजाय अपने डिब्बे से पैसे देता है।", "ऑनलाइन परीक्षेच्या एक आठवडा आधी अर्जुनच्या फोनची स्क्रीन फुटते. दुरुस्ती ₹900 ची आहे. अ‍ॅपकडून उधार घेण्याऐवजी तो आपल्या डब्यातून पैसे देतो."],
    try: [["Set a ₹1,000 savings goal in Money Lab.", "मनी लैब में ₹1,000 की बचत का लक्ष्य रखें।", "मनी लॅबमध्ये ₹1,000 चे बचत लक्ष्य ठेवा."], "tracker"],
    check: {
      q: ["Which is a fair use of an emergency fund?", "आपातकालीन फंड का सही इस्तेमाल कौन सा है?", "आपत्कालीन निधीचा योग्य वापर कोणता?"],
      o: [["A festival sale", "त्योहार की सेल", "सणाचा सेल"], ["A sudden medicine bill", "अचानक दवा का बिल", "अचानक आलेले औषधाचे बिल"], ["A friend's birthday gift", "दोस्त के जन्मदिन का तोहफा", "मित्राच्या वाढदिवसाची भेट"]],
      a: 1,
      why: ["It is for needs you could not plan for.", "यह उन ज़रूरतों के लिए है जिनकी योजना नहीं बन सकती थी।", "ज्या गरजांचे नियोजन करता आले नसते त्यांच्यासाठी हा निधी असतो."],
    },
  },
  "where-savings": {
    cat: "savings", icon: "landmark",
    points: [
      ["Money needed this month stays in a savings account.", "इस महीने की ज़रूरत का पैसा बचत खाते में रखें।", "या महिन्यात लागणारे पैसे बचत खात्यात ठेवा."],
      ["Money for next year can go in a fixed or recurring deposit.", "अगले साल के लिए पैसा एफडी या आरडी में रख सकते हैं।", "पुढच्या वर्षासाठीचे पैसे एफडी किंवा आरडीमध्ये ठेवता येतात."],
      ["Bank deposits are insured up to ₹5,00,000 per bank.", "बैंक में जमा पैसा हर बैंक में ₹5,00,000 तक बीमित होता है।", "बँकेतील ठेवींना प्रत्येक बँकेत ₹5,00,000 पर्यंत विमा संरक्षण असते."],
      ["A very high promised return usually hides a risk.", "बहुत ऊँचे मुनाफे के वादे में अक्सर जोखिम छिपा होता है।", "खूप जास्त परताव्याच्या आश्वासनामागे बहुधा धोका लपलेला असतो."],
    ],
    example: ["Sana saves ₹300 a month for next year's laptop in a recurring deposit at the post office. Her bus money stays in her savings account.", "सना अगले साल के लैपटॉप के लिए हर महीने ₹300 डाकघर की आरडी में डालती है। बस का पैसा बचत खाते में ही रहता है।", "सना पुढच्या वर्षीच्या लॅपटॉपसाठी दर महिन्याला ₹300 पोस्टाच्या आरडीमध्ये टाकते. बसचे पैसे बचत खात्यातच राहतात."],
    try: [["Ask at a bank or post office about the smallest recurring deposit.", "बैंक या डाकघर में सबसे छोटी आरडी के बारे में पूछें।", "बँकेत किंवा पोस्टात सर्वात लहान आरडीबद्दल विचारा."], null],
    check: {
      q: ["Where should next week's rent money sit?", "अगले हफ्ते के किराए का पैसा कहाँ रखें?", "पुढच्या आठवड्याच्या भाड्याचे पैसे कुठे ठेवावेत?"],
      o: [["A five-year deposit", "पाँच साल की एफडी में", "पाच वर्षांच्या एफडीत"], ["A savings account", "बचत खाते में", "बचत खात्यात"], ["A friend's scheme", "दोस्त की स्कीम में", "मित्राच्या योजनेत"]],
      a: 1,
      why: ["Money you need soon must be easy to take out.", "जो पैसा जल्दी चाहिए, वह आसानी से निकलना चाहिए।", "लवकर लागणारे पैसे सहज काढता यायला हवेत."],
    },
  },
  "what-sip": {
    cat: "savings", icon: "sprout",
    points: [
      ["A SIP puts a fixed amount into a mutual fund every month.", "एसआईपी में हर महीने तय रकम म्यूचुअल फंड में जाती है।", "एसआयपीमध्ये दर महिन्याला ठरलेली रक्कम म्युच्युअल फंडात जाते."],
      ["The value can go down as well as up.", "इसकी कीमत बढ़ भी सकती है और घट भी सकती है।", "त्याचे मूल्य वाढूही शकते आणि घटूही शकते."],
      ["It suits money you will not need for five years or more.", "यह उस पैसे के लिए है जो पाँच साल या ज़्यादा नहीं चाहिए।", "पाच वर्षे किंवा जास्त काळ न लागणाऱ्या पैशांसाठी हे योग्य आहे."],
      ["Build an emergency fund before you start one.", "इसे शुरू करने से पहले आपातकालीन फंड बना लें।", "हे सुरू करण्याआधी आपत्कालीन निधी तयार करा."],
    ],
    example: ["Vikram starts a ₹500 SIP with his first salary. In a bad year the value falls below what he put in. He keeps going because he will not need it for ten years.", "विक्रम पहली तनख्वाह से ₹500 की एसआईपी शुरू करता है। एक खराब साल में कीमत जमा रकम से नीचे चली जाती है। वह जारी रखता है, क्योंकि यह पैसा दस साल नहीं चाहिए।", "विक्रम पहिल्या पगारातून ₹500 ची एसआयपी सुरू करतो. एका वाईट वर्षात मूल्य भरलेल्या रकमेपेक्षा खाली जाते. तो सुरू ठेवतो, कारण हे पैसे दहा वर्षे लागणार नाहीत."],
    try: [["Check your savings goal in Money Lab before thinking about a SIP.", "एसआईपी सोचने से पहले मनी लैब में अपनी बचत का लक्ष्य देखें।", "एसआयपीचा विचार करण्याआधी मनी लॅबमधील बचत लक्ष्य पाहा."], "tracker"],
    check: {
      q: ["Does a SIP guarantee a profit?", "क्या एसआईपी मुनाफे की गारंटी देती है?", "एसआयपी नफ्याची हमी देते का?"],
      o: [["Yes, always", "हाँ, हमेशा", "हो, नेहमी"], ["No, the value can fall", "नहीं, कीमत गिर सकती है", "नाही, मूल्य घटू शकते"], ["Only in the first year", "सिर्फ पहले साल", "फक्त पहिल्या वर्षी"]],
      a: 1,
      why: ["A SIP is a habit of investing, not a promise.", "एसआईपी निवेश की आदत है, कोई वादा नहीं।", "एसआयपी ही गुंतवणुकीची सवय आहे, आश्वासन नाही."],
    },
  },
  inflation: {
    cat: "savings", icon: "arrow-up",
    points: [
      ["Inflation means prices rise a little every year.", "महँगाई यानी दाम हर साल थोड़े-थोड़े बढ़ते हैं।", "महागाई म्हणजे दरवर्षी किमती थोड्या थोड्या वाढतात."],
      ["The same ₹100 buys less next year.", "वही ₹100 अगले साल कम सामान खरीदते हैं।", "तेच ₹100 पुढच्या वर्षी कमी वस्तू घेतात."],
      ["Cash kept at home slowly loses value.", "घर में रखा नकद धीरे-धीरे कीमत खोता है।", "घरात ठेवलेली रोकड हळूहळू मूल्य गमावते."],
      ["Do not chase risky schemes to beat it.", "इसे हराने के लिए जोखिम वाली स्कीमों के पीछे न भागें।", "तिला हरवण्यासाठी धोकादायक योजनांच्या मागे धावू नका."],
    ],
    example: ["A plate of vada pav cost ₹12 a few years ago and costs ₹20 now. The plate is the same. The rupee buys less.", "कुछ साल पहले वड़ा पाव ₹12 का था, अब ₹20 का है। वड़ा पाव वही है। रुपया कम खरीद पाता है।", "काही वर्षांपूर्वी वडापाव ₹12 ला होता, आता ₹20 ला आहे. वडापाव तोच आहे. रुपयात कमी मिळते."],
    try: [["Ask a parent what a bus ticket cost when they were your age.", "माता-पिता से पूछें कि आपकी उम्र में बस का टिकट कितने का था।", "आईवडिलांना विचारा की तुमच्या वयात बसचे तिकीट किती होते."], null],
    check: {
      q: ["Prices rose 6 percent. Your savings earned 3 percent. You can now buy:", "दाम 6 प्रतिशत बढ़े। बचत पर 3 प्रतिशत मिला। अब आप खरीद सकते हैं:", "किमती 6 टक्के वाढल्या. बचतीवर 3 टक्के मिळाले. आता तुम्ही घेऊ शकता:"],
      o: [["More than before", "पहले से ज़्यादा", "आधीपेक्षा जास्त"], ["A little less than before", "पहले से थोड़ा कम", "आधीपेक्षा थोडे कमी"], ["Exactly the same", "बिलकुल उतना ही", "अगदी तेवढेच"]],
      a: 1,
      why: ["Prices grew faster than your money did.", "दाम आपके पैसे से तेज़ बढ़े।", "किमती तुमच्या पैशांपेक्षा वेगाने वाढल्या."],
    },
  },
  "tax-basics": {
    cat: "taxid", icon: "building",
    points: [
      ["Income tax applies only above a yearly income limit.", "आयकर सिर्फ सालाना आय की एक सीमा से ऊपर लगता है।", "आयकर फक्त वार्षिक उत्पन्नाच्या ठराविक मर्यादेपुढे लागतो."],
      ["Most students with pocket money or a small job owe nothing.", "जेब खर्च या छोटी नौकरी वाले ज़्यादातर छात्रों पर कोई कर नहीं बनता।", "खर्चाचे पैसे किंवा छोटी नोकरी असलेल्या बहुतेक विद्यार्थ्यांना कर लागत नाही."],
      ["GST is already inside the price of most things you buy.", "आप जो खरीदते हैं, उसकी कीमत में जीएसटी पहले से शामिल होता है।", "तुम्ही जे विकत घेता त्याच्या किमतीत जीएसटी आधीच असतो."],
      ["Keep payslips and receipts. They prove what you earned.", "सैलरी स्लिप और रसीदें रखें। ये आपकी कमाई का सबूत हैं।", "पगाराची स्लिप आणि पावत्या ठेवा. त्या तुमच्या कमाईचा पुरावा आहेत."],
    ],
    example: ["Tara earns ₹8,000 a month from tuitions, ₹96,000 a year. That is far below the limit, so she owes no income tax. A caller offering a “refund” for ₹500 is lying.", "तारा ट्यूशन से महीने के ₹8,000 कमाती है, साल के ₹96,000। यह सीमा से बहुत नीचे है, इसलिए उस पर कोई आयकर नहीं। ₹500 में “रिफंड” दिलाने वाला कॉलर झूठ बोल रहा है।", "तारा शिकवणीतून महिन्याला ₹8,000 कमावते, वर्षाला ₹96,000. हे मर्यादेपेक्षा खूप कमी आहे, म्हणून तिला आयकर लागत नाही. ₹500 मध्ये “रिफंड” मिळवून देणारा कॉलर खोटे बोलत आहे."],
    try: [["Look at a shop bill at home and find the GST line.", "घर पर किसी दुकान का बिल देखें और जीएसटी वाली लाइन ढूँढें।", "घरी एखादे दुकानाचे बिल पाहा आणि जीएसटीची ओळ शोधा."], null],
    check: {
      q: ["Someone offers to get you a tax refund for a fee, but you paid no tax. This is:", "कोई शुल्क लेकर टैक्स रिफंड दिलाने की बात करता है, पर आपने कर दिया ही नहीं। यह है:", "कोणी शुल्क घेऊन कर परतावा मिळवून देतो म्हणतो, पण तुम्ही कर भरलाच नाही. हे आहे:"],
      o: [["A good service", "अच्छी सेवा", "चांगली सेवा"], ["Very likely a scam", "बहुत संभव है कि ठगी", "बहुधा फसवणूक"], ["A government scheme", "सरकारी योजना", "सरकारी योजना"]],
      a: 1,
      why: ["There is nothing to refund if no tax was paid.", "जब कर दिया ही नहीं, तो वापस मिलने को कुछ नहीं।", "कर भरलाच नसेल तर परत मिळण्यासारखे काहीच नाही."],
    },
  },
  "why-pan": {
    cat: "taxid", icon: "id",
    points: [
      ["PAN is a ten-character number that links money to you.", "पैन दस अक्षरों का नंबर है जो पैसे को आपसे जोड़ता है।", "पॅन हा दहा अक्षरांचा क्रमांक आहे, जो पैशांना तुमच्याशी जोडतो."],
      ["You need it for a bank account, a job and larger payments.", "बैंक खाते, नौकरी और बड़े भुगतान के लिए यह चाहिए।", "बँक खाते, नोकरी आणि मोठ्या व्यवहारांसाठी तो लागतो."],
      ["Aadhaar proves who you are. Share it only where the law asks.", "आधार आपकी पहचान है। इसे वहीं दें जहाँ कानून माँगता है।", "आधार तुमची ओळख सिद्ध करते. कायद्याने लागते तिथेच द्या."],
      ["Never send a photo of either card in a chat to a stranger.", "किसी अनजान को चैट में दोनों में से किसी कार्ड की फोटो न भेजें।", "अनोळखी व्यक्तीला चॅटमध्ये कोणत्याही कार्डाचा फोटो पाठवू नका."],
    ],
    example: ["A stranger offers Rohan ₹500 for “just a photo” of his PAN and Aadhaar. With those two photos a loan can be taken in Rohan's name. He refuses.", "एक अनजान रोहन को पैन और आधार की “बस एक फोटो” के ₹500 देने को कहता है। इन दो फोटो से रोहन के नाम पर कर्ज लिया जा सकता है। वह मना कर देता है।", "एक अनोळखी व्यक्ती रोहनला पॅन आणि आधारच्या “फक्त एका फोटोसाठी” ₹500 देतो म्हणते. त्या दोन फोटोंवर रोहनच्या नावावर कर्ज घेता येते. तो नकार देतो."],
    try: [["Check where your PAN and Aadhaar cards are kept, and who has copies.", "देखें कि आपका पैन और आधार कहाँ रखा है, और किसके पास कॉपी है।", "तुमचे पॅन आणि आधार कुठे ठेवले आहे आणि प्रती कोणाकडे आहेत ते पाहा."], null],
    check: {
      q: ["Where is it safe to share your Aadhaar number?", "आधार नंबर कहाँ देना सुरक्षित है?", "आधार क्रमांक कुठे देणे सुरक्षित आहे?"],
      o: [["At the bank counter", "बैंक के काउंटर पर", "बँकेच्या काउंटरवर"], ["In a WhatsApp group", "व्हाट्सऐप ग्रुप में", "व्हॉट्सअ‍ॅप ग्रुपमध्ये"], ["On a link sent by SMS", "एसएमएस में आए लिंक पर", "एसएमएसने आलेल्या लिंकवर"]],
      a: 0,
      why: ["Share it in person at a known office, or on a site you typed yourself.", "इसे जाने-पहचाने दफ़्तर में खुद दें, या उस साइट पर जिसका पता आपने खुद लिखा हो।", "ओळखीच्या कार्यालयात स्वतः द्या, किंवा स्वतः पत्ता टाइप केलेल्या साइटवर."],
    },
  },
  "reading-fees": {
    cat: "loans", icon: "table",
    points: [
      ["Turn every percent into rupees.", "हर प्रतिशत को रुपयों में बदलें।", "प्रत्येक टक्का रुपयांत बदला."],
      ["Add all the lines: processing, documents, insurance, GST.", "सारी लाइनें जोड़ें: प्रोसेसिंग, दस्तावेज़, बीमा, जीएसटी।", "सगळ्या ओळी मिळवा: प्रोसेसिंग, कागदपत्रे, विमा, जीएसटी."],
      ["Ask which charges are optional, and refuse those you do not want.", "पूछें कौन से शुल्क ज़रूरी नहीं हैं, और जो नहीं चाहिए उन्हें मना करें।", "कोणती शुल्के ऐच्छिक आहेत ते विचारा आणि नको असलेली नाकारा."],
    ],
    example: ["A fee table shows 2 percent processing on ₹40,000, a ₹300 document charge and 18 percent GST on both. That is ₹800 plus ₹300 plus ₹198, so ₹1,298 in all.", "शुल्क तालिका में ₹40,000 पर 2 प्रतिशत प्रोसेसिंग, ₹300 दस्तावेज़ शुल्क और दोनों पर 18 प्रतिशत जीएसटी है। यानी ₹800, ₹300 और ₹198, कुल ₹1,298।", "शुल्क तक्त्यात ₹40,000 वर 2 टक्के प्रोसेसिंग, ₹300 कागदपत्र शुल्क आणि दोन्हींवर 18 टक्के जीएसटी आहे. म्हणजे ₹800, ₹300 आणि ₹198, एकूण ₹1,298."],
    try: [["Open the personal loan sample and add its two fees yourself.", "पर्सनल लोन का नमूना खोलें और दोनों शुल्क खुद जोड़ें।", "पर्सनल लोनचा नमुना उघडा आणि दोन्ही शुल्क स्वतः मिळवा."], "scan:personal-loan"],
    check: {
      q: ["2 percent processing fee on a ₹50,000 loan is:", "₹50,000 के कर्ज पर 2 प्रतिशत प्रोसेसिंग शुल्क कितना है?", "₹50,000 च्या कर्जावर 2 टक्के प्रोसेसिंग शुल्क किती?"],
      o: [["₹100", "₹100", "₹100"], ["₹1,000", "₹1,000", "₹1,000"], ["₹10,000", "₹10,000", "₹10,000"]],
      a: 1,
      why: ["One percent of 50,000 is 500, so two percent is 1,000.", "50,000 का एक प्रतिशत 500 है, तो दो प्रतिशत 1,000।", "50,000 चा एक टक्का 500, म्हणून दोन टक्के 1,000."],
    },
  },
  "before-you-sign": {
    cat: "loans", icon: "pen",
    points: [
      ["Ask how much reaches your hand after fees.", "पूछें कि शुल्क कटने के बाद हाथ में कितना आएगा।", "शुल्क कापल्यानंतर हातात किती येईल ते विचारा."],
      ["Ask for the total you repay, in rupees.", "पूछें कि कुल कितना लौटाना है, रुपयों में।", "एकूण किती परत द्यायचे ते रुपयांत विचारा."],
      ["Ask what one late month costs, in rupees.", "पूछें कि एक महीना देर होने पर कितने रुपये लगेंगे।", "एक महिना उशीर झाल्यास किती रुपये लागतील ते विचारा."],
      ["Take the paper home for a day. A fair lender will wait.", "कागज़ एक दिन के लिए घर ले जाएँ। सही कर्ज देने वाला रुक जाएगा।", "कागद एक दिवस घरी न्या. योग्य कर्जदाता थांबेल."],
    ],
    example: ["The agent says the offer ends tonight. Priya takes a photo of the paper, reads it with her mother, and returns the next morning. The offer is still there.", "एजेंट कहता है ऑफर आज रात खत्म है। प्रिया कागज़ की फोटो लेती है, माँ के साथ पढ़ती है और अगली सुबह लौटती है। ऑफर अब भी वहीं है।", "एजंट म्हणतो ऑफर आज रात्री संपते. प्रिया कागदाचा फोटो घेते, आईसोबत वाचते आणि दुसऱ्या दिवशी सकाळी परत जाते. ऑफर अजूनही तशीच आहे."],
    try: [["Scan a sample and read the questions to ask before you sign.", "एक नमूना स्कैन करें और साइन से पहले पूछने वाले सवाल पढ़ें।", "एक नमुना स्कॅन करा आणि सही करण्यापूर्वी विचारायचे प्रश्न वाचा."], "scan:personal-loan"],
    check: {
      q: ["“Sign now or lose the offer.” What is the calm reply?", "“अभी साइन करो वरना ऑफर गया।” शांत जवाब क्या है?", "“आत्ताच सही करा, नाहीतर ऑफर गेली.” शांत उत्तर काय?"],
      o: [["Sign quickly", "जल्दी साइन कर दूँ", "पटकन सही करीन"], ["“I will read it and come back.”", "“मैं पढ़कर वापस आऊँगा।”", "“मी वाचून परत येतो.”"], ["Pay a holding fee", "रोकने के लिए शुल्क दे दूँ", "थांबवण्यासाठी शुल्क भरीन"]],
      a: 1,
      why: ["Pressure is a cost too. A fair offer survives one night.", "दबाव भी एक कीमत है। सही ऑफर एक रात टिक जाता है।", "दबाव हीसुद्धा एक किंमत आहे. योग्य ऑफर एक रात्र टिकते."],
    },
  },
};
