import type { Lang } from "../catalog";

/** The few fixed sentences the on-device provider needs. Everything else it says is quoted from checked content. */
export const PHRASES: Record<Lang, Record<string, string>> = {
  en: {
    thanks: "You're welcome. Ask again any time.",
    greet: "Hello! Ask me anything about money in your own words: a word you don't understand, a form, a loan offer, or something in Verena's story. You could start with:",
    unknown: "I don't have a checked answer for that, so I won't guess. I can answer from Saath's guides, forms and story. Try asking about one of these:",
    noRates: "I don't quote today's interest rates, returns or prices, because they change and I can't check them from here. Look at the lender's or the regulator's own page for the current figure. What I can explain is how it works:",
    noAdvice: "I can't tell you what to buy or where to put your money. That depends on your whole situation, and I'm not a licensed adviser. Here is what the guides say about how to think it through:",
    points: "The main points:",
    more: "Read more:",
    here: "About what you're looking at",
    mistakeLead: "You picked “{picked}”. The better answer is “{correct}”.",
    mistakeWhy: "Why:",
    mistakeNext: "This guide covers it:",
    reviseLead: "Based on what you've done so far, this is what I'd go back to:",
    reviseFocus: "You said these areas are hard for you: {topics}.",
    reviseWeak: "You've had wrong answers in: {topics}.",
    reviseNone: "You're up to date. Nothing needs revising today. Carry on with the story or read a new guide.",
    summary: "You are on level {level} with {xp} XP and a {streak}-day streak. You've read {lessonsDone} of {lessonsTotal} guides and finished {episodesDone} of {episodesTotal} story episodes.",
    summaryStage: "In the story, Verena is at: {stage}.",
    summaryNext: "Next, I'd suggest:",
    formLead: "{title}:",
    formUnknown: "I don't have that form in the library yet, so I can't explain it reliably. Check the issuer's official website, and never sign a form with blank fields.",
    photoNone: "No fields I recognise were read from the photo, so I can't explain it. Try a sharper photo in good light, or look the form up in the library.",
    photoLead: "From the photo, these are the fields I recognised:",
    emergency: "If money has just been taken from you or you shared an OTP: call 1930 (the national cyber crime helpline) now and tell your bank straight away. You can also report at cybercrime.gov.in. Speed matters more than anything else.",
    offline: "(Answered on this device from Saath's checked guides.)",
  },
  hi: {
    thanks: "आपका स्वागत है। कभी भी फिर पूछें।",
    greet: "नमस्ते! पैसों के बारे में अपने शब्दों में कुछ भी पूछें: कोई शब्द जो समझ न आए, कोई फ़ॉर्म, लोन का ऑफ़र, या वेरेना की कहानी की कोई बात। शुरुआत इनसे कर सकते हैं:",
    unknown: "इसका जाँचा हुआ जवाब मेरे पास नहीं है, इसलिए मैं अंदाज़ा नहीं लगाऊँगी। मैं साथ की गाइड, फ़ॉर्म और कहानी से जवाब दे सकती हूँ। इनमें से कुछ पूछकर देखें:",
    noRates: "मैं आज की ब्याज दर, रिटर्न या भाव नहीं बताती, क्योंकि ये बदलते रहते हैं और यहाँ से जाँचे नहीं जा सकते। ताज़ा आँकड़ा ऋणदाता या नियामक की अपनी वेबसाइट पर देखें। यह कैसे काम करता है, वह मैं समझा सकती हूँ:",
    noAdvice: "क्या खरीदें या पैसा कहाँ लगाएँ, यह मैं नहीं बता सकती। यह आपकी पूरी स्थिति पर निर्भर है और मैं लाइसेंस प्राप्त सलाहकार नहीं हूँ। सोचने का तरीका गाइड में यह है:",
    points: "मुख्य बातें:",
    more: "और पढ़ें:",
    here: "आप जो देख रहे हैं उसके बारे में",
    mistakeLead: "आपने “{picked}” चुना। बेहतर जवाब है “{correct}”।",
    mistakeWhy: "क्यों:",
    mistakeNext: "यह गाइड इसे समझाती है:",
    reviseLead: "अब तक आपने जो किया है, उसके हिसाब से मैं इन्हें दोहराऊँगी:",
    reviseFocus: "आपने बताया था कि ये विषय कठिन लगते हैं: {topics}।",
    reviseWeak: "इन विषयों में आपके जवाब गलत हुए हैं: {topics}।",
    reviseNone: "आप पूरी तरह तैयार हैं। आज कुछ दोहराने की ज़रूरत नहीं। कहानी आगे बढ़ाएँ या नई गाइड पढ़ें।",
    summary: "आप स्तर {level} पर हैं, {xp} XP और {streak} दिन की लय के साथ। आपने {lessonsTotal} में से {lessonsDone} गाइड पढ़ी हैं और कहानी के {episodesTotal} में से {episodesDone} भाग पूरे किए हैं।",
    summaryStage: "कहानी में वेरेना यहाँ है: {stage}।",
    summaryNext: "आगे के लिए मेरा सुझाव:",
    formLead: "{title}:",
    formUnknown: "यह फ़ॉर्म अभी लाइब्रेरी में नहीं है, इसलिए मैं इसे भरोसे से नहीं समझा सकती। जारी करने वाली संस्था की आधिकारिक वेबसाइट देखें, और खाली जगह वाले फ़ॉर्म पर कभी दस्तखत न करें।",
    photoNone: "फ़ोटो से ऐसा कोई खाना नहीं पढ़ा गया जिसे मैं पहचानती हूँ, इसलिए मैं इसे समझा नहीं सकती। अच्छी रोशनी में साफ़ फ़ोटो लें, या फ़ॉर्म को लाइब्रेरी में खोजें।",
    photoLead: "फ़ोटो से मैंने ये खाने पहचाने:",
    emergency: "अगर अभी-अभी पैसा गया है या आपने OTP बता दिया है: तुरंत 1930 (राष्ट्रीय साइबर अपराध हेल्पलाइन) पर फ़ोन करें और अपने बैंक को बताएँ। cybercrime.gov.in पर भी शिकायत कर सकते हैं। जल्दी करना सबसे ज़रूरी है।",
    offline: "(जवाब इसी फ़ोन पर, साथ की जाँची हुई गाइड से दिया गया।)",
  },
  mr: {
    thanks: "आनंद झाला. कधीही पुन्हा विचारा.",
    greet: "नमस्कार! पैशांबद्दल तुमच्या शब्दांत काहीही विचारा: न समजलेला शब्द, एखादा फॉर्म, कर्जाची ऑफर, किंवा वेरेनाच्या गोष्टीतली एखादी गोष्ट. सुरुवात यांनी करू शकता:",
    unknown: "याचे तपासलेले उत्तर माझ्याकडे नाही, म्हणून मी अंदाज लावणार नाही. मी साथच्या मार्गदर्शिका, फॉर्म आणि गोष्टीतून उत्तर देऊ शकते. यापैकी काही विचारून पाहा:",
    noRates: "मी आजचा व्याजदर, परतावा किंवा भाव सांगत नाही, कारण ते बदलत राहतात आणि इथून तपासता येत नाहीत. ताजा आकडा कर्ज देणाऱ्याच्या किंवा नियामकाच्या स्वतःच्या संकेतस्थळावर पाहा. हे कसे चालते ते मी समजावू शकते:",
    noAdvice: "काय घ्यावे किंवा पैसे कुठे गुंतवावेत हे मी सांगू शकत नाही. ते तुमच्या संपूर्ण परिस्थितीवर अवलंबून आहे आणि मी परवानाधारक सल्लागार नाही. विचार कसा करावा हे मार्गदर्शिकेत असे आहे:",
    points: "मुख्य मुद्दे:",
    more: "अधिक वाचा:",
    here: "तुम्ही जे पाहत आहात त्याबद्दल",
    mistakeLead: "तुम्ही “{picked}” निवडले. अधिक योग्य उत्तर “{correct}” आहे.",
    mistakeWhy: "का:",
    mistakeNext: "ही मार्गदर्शिका ते समजावते:",
    reviseLead: "आतापर्यंत तुम्ही जे केले त्यावरून मी हे पुन्हा पाहीन:",
    reviseFocus: "तुम्ही सांगितले होते की हे विषय अवघड वाटतात: {topics}.",
    reviseWeak: "या विषयांत तुमची उत्तरे चुकली आहेत: {topics}.",
    reviseNone: "तुम्ही अगदी तयार आहात. आज काही उजळणी करायची गरज नाही. गोष्ट पुढे न्या किंवा नवी मार्गदर्शिका वाचा.",
    summary: "तुम्ही स्तर {level} वर आहात, {xp} XP आणि {streak} दिवसांच्या सातत्यासह. तुम्ही {lessonsTotal} पैकी {lessonsDone} मार्गदर्शिका वाचल्या आहेत आणि गोष्टीचे {episodesTotal} पैकी {episodesDone} भाग पूर्ण केले आहेत.",
    summaryStage: "गोष्टीत वेरेना इथे आहे: {stage}.",
    summaryNext: "पुढे माझी सूचना:",
    formLead: "{title}:",
    formUnknown: "हा फॉर्म अजून संग्रहात नाही, म्हणून मी तो खात्रीने समजावू शकत नाही. तो जारी करणाऱ्या संस्थेचे अधिकृत संकेतस्थळ पाहा, आणि रिकाम्या जागा असलेल्या फॉर्मवर कधीही सही करू नका.",
    photoNone: "फोटोतून मला ओळखता येईल असा एकही रकाना वाचला गेला नाही, म्हणून मी तो समजावू शकत नाही. चांगल्या प्रकाशात स्पष्ट फोटो घ्या, किंवा फॉर्म संग्रहात शोधा.",
    photoLead: "फोटोतून मी हे रकाने ओळखले:",
    emergency: "आत्ताच पैसे गेले असतील किंवा तुम्ही OTP सांगितला असेल: लगेच 1930 (राष्ट्रीय सायबर गुन्हे हेल्पलाइन) वर फोन करा आणि तुमच्या बँकेला कळवा. cybercrime.gov.in वरही तक्रार करता येते. वेळ सर्वात महत्त्वाचा आहे.",
    offline: "(उत्तर याच फोनवर, साथच्या तपासलेल्या मार्गदर्शिकांमधून दिले.)",
  },
};
